using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace WindowsFormsApplication1.Class
{
    public class ItinerarySummaryDetail
    {
        public int TravelItinerary_Summary_TransSumID_ID;
        public int TravelItinerary_Summary_TransactionID_NB;
        public int TravelItinerary_Summary_CustomerID_NB;
        public int TravelItinerary_Summary_CompanyID_NB;
        public string TravelItinerary_Summary_ServicesUsed_CH;
        public int TravelItinerary_Summary_NumberOfService_NB;
        public decimal TravelItinerary_Summary_NetAmount_NU;
        public string TravelItinerary_Summary_PaymentType_CH;
        public decimal TravelItinerary_Summary_PaymentCharges_NU;
        public string TravelItinerary_Summary_ContactEmail_VC;
        public string TravelItinerary_Summary_ContactPhone_VC;
        public string TravelItinerary_Summary_ContactMobile_VC;
        public string TravelItinerary_Summary_BookingStatus_CH;
        public string TravelItinerary_Summary_CurrentStatus_CH;
        public string TravelItinerary_Summary_RequestedFrom_CH;
        public int TravelItinerary_Summary_RecordStatus_NB;
        public DateTime TravelItinerary_Summary_CreatedDate_DT;
        public DateTime TravelItinerary_Summary_ModifiedDate_DT;
        public int TravelItinerary_Summary_CreatedUser_NB;
        public int TravelItinerary_Summary_ModifiedUser_NB;
        public string TravelItinerary_Summary_Remarks_VC;
        public string TravelItinerary_Summary_AUI_VC;
        public string TravelItinerary_Summary_UTL_VC;
        public string TravelItinerary_Summary_UPL_VC;
        public string TravelItinerary_Summary_WORKFLOWCODE_VC;
        public string TravelItinerary_Summary_Title_VC;
        public string TravelItinerary_Summary_FirstName_VC;
        public string TravelItinerary_Summary_LastName_VC;
        public string TravelItinerary_Summary_Address_VC;
        public string TravelItinerary_Summary_Country_VC;
        public string TravelItinerary_Summary_State_VC;
        public string TravelItinerary_Summary_City_VC;
        public string TravelItinerary_Summary_Pincode_VC;
        public string TravelItinerary_Summary_FYearID_VC;
        public string TravelItinerary_Summary_UserType_VC;
        public string TravelItinerary_Summary_CompanyType_VC;
        public string TravelItinerary_Summary_GroupID_VC;
        public string TravelItinerary_Summary_ServiceCode_VC;
        public string TravelItinerary_Summary_SectorType_VC;
        public DateTime TravelItinerary_Summary_TransactionDate_DT;
        public long TravelItinerary_Summary_IsOnline_BL;
        public string TravelItinerary_Summary_PaymentGateWay_VC;
        public string TravelItinerary_Summary_PaymentStatus_CH;
        public string TravelItinerary_Summary_SID_VC;
        public decimal TravelItinerary_Summary_INRExchangeRate_NU;
        public string TravelItinerary_Summary_DealCode_VC;
        public string TravelItinerary_Summary_ForceFailBookingStatus_CH;
        public decimal TravelItinerary_Summary_DifferentialAmount_NU;
        public int TravelItinerary_Summary_CorperateCard_NB;
        public int TravelItinerary_Summary_RefTransactionID_NB;
        public decimal TravelItinerary_Summary_CouponAmount_NU;
        public string TravelItinerary_Summary_CouponType_VC;
        public decimal TravelItinerary_Summary_CouponBalance_NU;
        public decimal TravelItinerary_Summary_AirlineBalanceDue_NU;
        public decimal TravelItinerary_Summary_SSRAmount_NU;
        public string TravelItinerary_Summary_LANIP_VC;
        public string TravelItinerary_Summary_WANIP_VC;
        public int TravelItinerary_Summary_RequestSource_NB;
        public string TravelItinerary_Summary_RefServiceType_VC;
        public decimal TravelItinerary_Summary_SupplierAmount_NU;
        public string TravelItinerary_Summary_OtherAccount_VC;
        public decimal TravelItinerary_Summary_CumulativeNetAmount_NU;
        public int TravelItinerary_Summary_SequenceID_NB;
        public decimal TravelItinerary_Summary_RefServiceNetAmount_NU;
        public long TravelItinerary_Summary_IsFlightPlusHotel;
        public string TravelItinerary_Summary_CardType;
        public int TravelItinerary_Summary_Score;
        public string TravelItinerary_Summary_dId_VC;
        public string TravelItinerary_Summary_RMSStatus_VC;
        public string TravelItinerary_Summary_AppVersion_VC;
        public int TravelItinerary_Summary_NoOfDays_NB;
        public string TravelItinerary_Summary_GSTCustomerTIN_VC;
        public string TravelItinerary_Summary_GSTHolderName_VC;
        public string TravelItinerary_Summary_GSTPartyState_VC;
        public string TravelItinerary_Summary_GSTRegdEmail_VC;
        public string TravelItinerary_Summary_GSTRegdPhoneNumber_VC;
        public string TravelItinerary_Summary_GSTRegdAddress_VC;
        public decimal TravelItinerary_Summary_PaymentConventionalCharges_NU;
        public int TravelItinerary_Summary_APMRefTransactionID_NB;

    }
}
